### ISSUE TITLE
{"detail":"Missing Cookie fastapi-csrf-token"}

### ISSUE THREAD

**Issue by Nebulizer1213** [aekazitt/fastapi-csrf-protect#7]
https://pastecord.com/ewisabacyb.py I no longer get the error I sent before. I now get this {"detail":"Missing Cookie fastapi-csrf-token"}

**Comment by Nebulizer1213** [comment]
is there a way to make it so I dont need to use the csrf cookie at all?

**Comment by aekazitt** [comment]
You used `set_csrf_cookie` in a Response object.
And then returned a different TemplateResponse object in your GET endpoint.
See example in README for details on how to `set_csrf_cookie`

**Comment by aekazitt** [comment]
> is there a way to make it so I dont need to use the csrf cookie at all?

See example titled `With Context and Headers` on README
- This one is more tedious since it requires more works using passed context object 
(See: https://fastapi.tiangolo.com/advanced/templates/#using-jinja2templates)
- Using the passed object to set the header of the POST request manually (via JavaScript)
(See: https://masteringjs.io/tutorials/axios/headers)

Good luck.
